/* asis-proofs.js — live re-derivation of the verified ASIS decode results.
   Everything computable in-browser is recomputed from the embedded binaire.bin here;
   the two Monte-Carlo proofs (blind-clock null, closed-loop SMILES) are cited from their
   saved manifests (see data-* provenance). No external deps. House palette.        */
(function(global){
  'use strict';
  const N = 256, TSTAR = 6625, POP = 625;
  const B64 = "//8GkChBRIhEiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAoAAAAAAAAAACAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGBEAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgACAEAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAACBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAgAGDAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAgAANAAAAAAAAABAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAIAAAAAAAAAAAAABgYBAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAGBkAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAARAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAIAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAIAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQA0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAgQAAIAAAAAAAAAAEGAAAAAAAAAAAAAAAAAAAAAAAAAEABAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEEAAQAAAAAAAAAAAAAAAAAAAAAAEYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBgQAAAAAACAAAAAAAABIAAAAAAAAAAAAAAAAAAAAAEAACAAAAAAAUAAAAAAAgBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAJAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQBYMEAAAABAAAAAAAAAAAAAAAAgBIECAAAAAAAAAAAgAAAwAAAAAAAAAAAAAAAAAAAAAAAAAQgAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARGBwAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAYGAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAQAAgAAQIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIQAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAQAAAAAwAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAEADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgIAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAECAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAIAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAEAAAAADgACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGABAAAAAAAAAAAAAADAgAAAAAAAAAAAAAAAAAAAAAAgIAQgAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAgACEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaAADIAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACBoAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABCUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAACBgAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAABAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIGIAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABACAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIQBAAAAAAAAAAAAAAABQAAAAAAAAAAAAAAAAAAAgAABgAAAAAAAAAAAAAAAAAAQAAAAIAAAAAAAAAAAAAABIAOLAQAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAgAAgBMEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgYAAkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWBwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBAIACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAQAAAAAAAAAAAAAAAAAAAAAAAAAcAAAAAAAAAAAAAACAEgAAAAAAAAAAAAAAAAEAAAAAABgAAAAAAAAAAAAAACCAAAAAAAAAAAAAgAAAAAAAAAAIIAAAAAAAAAAAAAAAQMABAAAAAAAAAAGAAAAAgAAAAACIAAAAAAAAAAAAAAAAxoAAAAAAAAAAAAAAAAAAAABIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAoAAAAAAIBABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAEBgAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAQYAAAAAAAAAAAAAABgIAAAAAAAAAAAAAAAAAAAAAgAABhwIBAAAAAAAAAIAYAAAAAAAAAAAAAAAAAAAAAAAAAAADIBAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAASAEQAAAAAAAAAAAAAAAAAAAAAAYGCAAAAAAAAAAAABAAAIAAAAAAAAAAAAAAAAAAAAAABgYIAEAAAAAAAAAAAIAAgAAAAAAAAAAAAAAAAAAAAAAABiACAAAAAAAAAAAAQAEgAAACAAAAAAAAAAAAAAAAAAAAgADAAAAAAAAAAAAAAaAAAAAAAAAAAAAAAAAAAAAgIAAAAcAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAABAAAgAAAAAAAAAAAAAhAAAABAAAAAAAAAAAAAAAAAAQBJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQCTI0AAAAAAAAAAAAAAAAAAAoAAAAAAAAAAAAAACABAAAMDAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAA0CAAAAAAAAAAAAAAAAIEAAAAAABAAAAAAAAAAAAAAIDAAIAAAAAAAAAAAAAAwAIAAAAAABAAAAAAAAAAAAADAAADEAAAAAAAAAAABADAAIAAAAAAAAAAAAAAAAAAACAAAAgWAAAAAAAAAAAAAAAAAAAAAAQQAAAAAAAAAAAAAAAAAU4AAAAAAAAAAAgAAAAAAAAAAEAAAAAAAAAAACAAAAHADAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAQAABgAAAAAAAAAAAAEAAAAAAAAAQAAAAAAAAAAAAAEAAAAACAAAAAAAAAAAAAAAAAAAAQAAAgAAAAAAAAAABACAAIAAAAAAAAAAAAAAAAAAAAAAAAmAAAAAAAAAAAAAIAgAIAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABhEAAAAAAAAAQAABABAAAAAAAAAAAAAAAAAAKAAAAAEAQEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAQAAAAAEACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABARgwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIhgYAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwEAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAIEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAIDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIYAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgCIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAGQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIACgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+D4AAAAAAAAP/w==";

  // ---- decode embedded payload (bytes 10 .. len-10 = 8192 message bytes) ----
  function payload(){
    const bin = atob(B64), raw = new Uint8Array(bin.length);
    for(let i=0;i<bin.length;i++) raw[i]=bin.charCodeAt(i);
    return { raw, msg: raw.slice(10, raw.length-10) };
  }
  function unpack(msg){
    const g = new Uint8Array(N*N);
    for(let i=0;i<8192;i++){ const b=msg[i]; for(let k=0;k<8;k++) g[i*8+k]=(b>>(7-k))&1; }
    return g;
  }
  // ---- the exact Margolus stepper (single-rotation CW, offset flips each gen) ----
  function stepM(g,t){
    const off=t&1;
    for(let by=0;by<N;by+=2) for(let bx=0;bx<N;bx+=2){
      const y0=(by+off)%N,x0=(bx+off)%N,y1=(y0+1)%N,x1=(x0+1)%N;
      const ia=y0*N+x0,ib=y0*N+x1,ic=y1*N+x0,id=y1*N+x1;
      const a=g[ia],b=g[ib],c=g[ic],d=g[id];
      if(a+b+c+d===1){ g[ia]=c; g[ib]=a; g[ic]=d; g[id]=b; }
    }
  }
  function popcount(g){ let s=0; for(let i=0;i<g.length;i++) s+=g[i]; return s; }

  // ---- 8-connected component census ----
  function census(g){
    const lab=new Int32Array(N*N).fill(0); let cur=0; const sizes=[];
    const stack=[];
    for(let p=0;p<N*N;p++){
      if(g[p]&&!lab[p]){
        cur++; let sz=0; stack.length=0; stack.push(p); lab[p]=cur;
        while(stack.length){
          const q=stack.pop(); sz++;
          const qy=(q/N)|0, qx=q%N;
          for(let dy=-1;dy<=1;dy++) for(let dx=-1;dx<=1;dx++){
            if(!dy&&!dx) continue;
            const ny=qy+dy, nx=qx+dx;
            if(ny<0||ny>=N||nx<0||nx>=N) continue;
            const r=ny*N+nx;
            if(g[r]&&!lab[r]){ lab[r]=cur; stack.push(r); }
          }
        }
        sizes.push(sz);
      }
    }
    const hist={}; sizes.forEach(s=>hist[s]=(hist[s]||0)+1);
    return { hist, ncomp:cur, sizes };
  }

  // ---- header: 4x4 Margolus states + rule check ----
  function headerProof(raw){
    const hb=[]; for(let i=2;i<10;i++) for(let k=0;k<8;k++) hb.push((raw[i]>>(7-k))&1);
    const states=[]; for(let s=0;s<4;s++){ const m=[]; for(let r=0;r<4;r++){const row=[];
      for(let c=0;c<4;c++) row.push(hb[s*16+r*4+c]); m.push(row);} states.push(m); }
    function step4(g,t){ const off=t&1, o=g.map(r=>r.slice());
      for(let by=0;by<4;by+=2) for(let bx=0;bx<4;bx+=2){
        const y0=(by+off)%4,x0=(bx+off)%4,y1=(y0+1)%4,x1=(x0+1)%4;
        const a=g[y0][x0],b=g[y0][x1],c=g[y1][x0],d=g[y1][x1];
        if(a+b+c+d===1){ o[y0][x0]=c;o[y0][x1]=a;o[y1][x0]=d;o[y1][x1]=b; } }
      return o; }
    const eq=(A,B)=>A.every((r,i)=>r.every((v,j)=>v===B[i][j]));
    const chain=[]; for(let s=0;s<3;s++) chain.push(eq(step4(states[s],s),states[s+1]));
    return { states, chain, ok:chain.every(x=>x),
             hex:[...raw.slice(0,10)].map(b=>b.toString(16).padStart(2,'0')).join(' ') };
  }
  // ---- footer: run-length product ----
  function footerProof(raw){
    const fb=[]; const f=raw.slice(raw.length-10);
    for(let i=0;i<10;i++) for(let k=0;k<8;k++) fb.push((f[i]>>(7-k))&1);
    const runs=[]; let cur=fb[0],n=1;
    for(let i=1;i<fb.length;i++){ if(fb[i]===cur) n++; else {runs.push([cur,n]);cur=fb[i];n=1;} }
    runs.push([cur,n]);
    const counts=runs.slice(0,4).map(r=>r[1]);
    const prod=counts.reduce((a,b)=>a*b,1);
    return { runs, counts, prod, ok:prod===TSTAR,
             hex:[...f].map(b=>b.toString(16).padStart(2,'0')).join(' ') };
  }

  // ---- full live derivation (async so the UI can show progress) ----
  function derive(onProgress){
    return new Promise(resolve=>{
      const {raw,msg}=payload(); const seed=unpack(msg);
      const seedPop=popcount(seed);
      const hp=headerProof(raw), fp=footerProof(raw);
      // evolve to 6625 in chunks, reporting progress
      const g=seed.slice(); let t=0;
      function chunk(){
        const end=Math.min(t+500,TSTAR);
        for(;t<end;t++) stepM(g,t);
        if(onProgress) onProgress(t/TSTAR);
        if(t<TSTAR){ setTimeout(chunk,0); }
        else {
          const finalPop=popcount(g);
          const cen=census(g);
          resolve({ seedPop, finalPop, conserved:seedPop===finalPop&&finalPop===POP,
                    census:cen, header:hp, footer:fp });
        }
      }
      setTimeout(chunk,0);
    });
  }

  global.ASISProofs = { derive, payload, census, TSTAR, POP, N };
})(window);
